language: go
go:
  - 1.11.1
install:
  - go get github.com/Masterminds/glide
  - go get golang.org/x/lint/golint
before_script:
script:
  - glide install
  - GO15VENDOREXPERIMENT=1 go build .
  - GO15VENDOREXPERIMENT=1 go test $(glide novendor)